# Generated by Django 5.0.7 on 2024-08-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_subtask_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
