# Generated by Django 5.0.7 on 2024-08-08 14:04

from django.db import migrations


def add_user_dailytask(app, schema_editor):
    DailyTask = app.get_model("taskmanager", "DailyTask")
    User = app.get_model("auth", "User")

    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        DailyTask.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ("taskmanager", "0004_dailytask_user"),
    ]

    operations = [migrations.RunPython(add_user_dailytask)]
