# Generated by Django 5.0.7 on 2024-08-04 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='notes/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
