# Generated by Django 5.0.7 on 2024-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_viewd',
            field=models.BooleanField(default=False),
        ),
    ]
