# Generated by Django 5.0.7 on 2024-08-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_is_viewd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='is_viewd',
            new_name='is_viewed',
        ),
    ]
