# Generated by Django 5.0.7 on 2024-08-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_is_viewd_notes_is_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='images',
            new_name='image',
        ),
    ]
