# Generated by Django 5.0.7 on 2024-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_images_notes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
