# Generated by Django 5.0.7 on 2024-08-08 13:35

from django.db import migrations


def add_user(app, schema_editor):
    Notes = app.get_model("notes", "Notes")
    User = app.get_model("auth", "User")

    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        Notes.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_notes_user"),
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
