# Generated by Django 5.0.7 on 2024-08-08 15:13

from django.db import migrations


def add_user(app, schema_editor):
    Profile = app.get_model("home", "Profile")
    User = app.get_model("auth", "User")

    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        Profile.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_profile_user"),
    ]

    operations = [migrations.RunPython(add_user)]
