# Generated by Django 5.0.7 on 2024-08-06 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_resources', '0002_bookmark_delete_resourceslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
