# Generated by Django 5.0.7 on 2024-08-08 13:52

from django.db import migrations


def add_user(app, schema_editor):
    Bookmark = app.get_model("study_resources", "Bookmark")
    User = app.get_model("auth", "User")

    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        Bookmark.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ("study_resources", "0005_bookmark_user"),
    ]

    operations = [migrations.RunPython(add_user)]
