# Generated by Django 5.0.7 on 2024-08-08 13:58

from django.db import migrations


def add_user_videos(app, schema_editor):
    Video = app.get_model("study_resources", "Video")
    User = app.get_model("auth", "User")

    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        Video.objects.filter(user__isnull=True).update(user=superuser)


class Migration(migrations.Migration):
    dependencies = [
        ("study_resources", "0008_video_user"),
    ]

    operations = [migrations.RunPython(add_user_videos)]
